
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameCombat
{
public sealed partial class CampaignCfg : Luban.BeanBase
{
    public CampaignCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Squads = new System.Collections.Generic.Dictionary<string, GameCombat.SquadStance[]>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { string _k0;  _k0 = _buf.ReadString(); GameCombat.SquadStance[] _v0;  {int __n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);_v0 = new GameCombat.SquadStance[__n1];for(var __index1 = 0 ; __index1 < __n1 ; __index1++) { GameCombat.SquadStance __e1;__e1 = GameCombat.SquadStance.DeserializeSquadStance(_buf); _v0[__index1] = __e1;}}     Squads.Add(_k0, _v0);}}
    }

    public static CampaignCfg DeserializeCampaignCfg(ByteBuf _buf)
    {
        return new GameCombat.CampaignCfg(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 军队名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 小队名称
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, GameCombat.SquadStance[]> Squads;
   
    public const int __ID__ = -1609721652;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "squads:" + Luban.StringUtil.CollectionToString(Squads) + ","
        + "}";
    }
}

}

