
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameCombat
{
public sealed partial class SquadStance : Luban.BeanBase
{
    public SquadStance(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Row = _buf.ReadInt();
        Column = _buf.ReadInt();
    }

    public static SquadStance DeserializeSquadStance(ByteBuf _buf)
    {
        return new GameCombat.SquadStance(_buf);
    }

    /// <summary>
    /// 角色id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 排
    /// </summary>
    public readonly int Row;
    /// <summary>
    /// 列
    /// </summary>
    public readonly int Column;
   
    public const int __ID__ = 951823266;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "row:" + Row + ","
        + "column:" + Column + ","
        + "}";
    }
}

}

