
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameCombat
{
public partial class TbCampaign
{
    private readonly System.Collections.Generic.Dictionary<int, GameCombat.CampaignCfg> _dataMap;
    private readonly System.Collections.Generic.List<GameCombat.CampaignCfg> _dataList;
    
    public TbCampaign(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameCombat.CampaignCfg>();
        _dataList = new System.Collections.Generic.List<GameCombat.CampaignCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameCombat.CampaignCfg _v;
            _v = GameCombat.CampaignCfg.DeserializeCampaignCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameCombat.CampaignCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<GameCombat.CampaignCfg> DataList => _dataList;

    public GameCombat.CampaignCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameCombat.CampaignCfg Get(int key) => _dataMap[key];
    public GameCombat.CampaignCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

