
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class Audio : Luban.BeanBase
{
    public Audio(ByteBuf _buf) 
    {
        EnterBtn = _buf.ReadString();
        ClickBtn = _buf.ReadString();
        EnterTgl = _buf.ReadString();
        ClickTgl = _buf.ReadString();
        DragBarMusic = _buf.ReadString();
        DragBarSfx = _buf.ReadString();
        MainMenuBgm = _buf.ReadString();
        GameBgm = _buf.ReadString();
        PopOut = _buf.ReadString();
        PopMove = _buf.ReadString();
        PopHide = _buf.ReadString();
    }

    public static Audio DeserializeAudio(ByteBuf _buf)
    {
        return new Audio(_buf);
    }

    /// <summary>
    /// 按钮_悬停
    /// </summary>
    public readonly string EnterBtn;
    /// <summary>
    /// 按钮_点击
    /// </summary>
    public readonly string ClickBtn;
    /// <summary>
    /// 切换_悬停
    /// </summary>
    public readonly string EnterTgl;
    /// <summary>
    /// 切换_点击
    /// </summary>
    public readonly string ClickTgl;
    /// <summary>
    /// 进度条_拖拽_测试音乐
    /// </summary>
    public readonly string DragBarMusic;
    /// <summary>
    /// 进度条_拖拽_测试音效
    /// </summary>
    public readonly string DragBarSfx;
    /// <summary>
    /// 主菜单_背景乐
    /// </summary>
    public readonly string MainMenuBgm;
    /// <summary>
    /// 游戏_背景乐
    /// </summary>
    public readonly string GameBgm;
    /// <summary>
    /// 弹窗_弹出
    /// </summary>
    public readonly string PopOut;
    /// <summary>
    /// 弹窗_移动
    /// </summary>
    public readonly string PopMove;
    /// <summary>
    /// 弹窗_隐藏
    /// </summary>
    public readonly string PopHide;
   
    public const int __ID__ = 63613878;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "enterBtn:" + EnterBtn + ","
        + "clickBtn:" + ClickBtn + ","
        + "enterTgl:" + EnterTgl + ","
        + "clickTgl:" + ClickTgl + ","
        + "dragBarMusic:" + DragBarMusic + ","
        + "dragBarSfx:" + DragBarSfx + ","
        + "mainMenuBgm:" + MainMenuBgm + ","
        + "gameBgm:" + GameBgm + ","
        + "popOut:" + PopOut + ","
        + "popMove:" + PopMove + ","
        + "popHide:" + PopHide + ","
        + "}";
    }
}

}

