
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
public partial class Tables
{
    public Global.TbGSingleton TbGSingleton {get; }
    public Character.TbAdventurer TbAdventurer {get; }
    public Character.TbClass TbClass {get; }
    public Character.TbSubrace TbSubrace {get; }
    public Character.TbItem TbItem {get; }
    public Character.TbWeaponBase TbWeaponBase {get; }
    public Character.TbAbility TbAbility {get; }
    public Character.TbPreset TbPreset {get; }
    public Combat.TbCampaign TbCampaign {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbGSingleton = new Global.TbGSingleton(loader("global_tbgsingleton"));
        TbAdventurer = new Character.TbAdventurer(loader("character_tbadventurer"));
        TbClass = new Character.TbClass(loader("character_tbclass"));
        TbSubrace = new Character.TbSubrace(loader("character_tbsubrace"));
        TbItem = new Character.TbItem(loader("character_tbitem"));
        TbWeaponBase = new Character.TbWeaponBase(loader("character_tbweaponbase"));
        TbAbility = new Character.TbAbility(loader("character_tbability"));
        TbPreset = new Character.TbPreset(loader("character_tbpreset"));
        TbCampaign = new Combat.TbCampaign(loader("combat_tbcampaign"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGSingleton.ResolveRef(this);
        TbAdventurer.ResolveRef(this);
        TbClass.ResolveRef(this);
        TbSubrace.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbWeaponBase.ResolveRef(this);
        TbAbility.ResolveRef(this);
        TbPreset.ResolveRef(this);
        TbCampaign.ResolveRef(this);
    }
}

}
