
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
public partial class Tables
{
    public TbAudio TbAudio {get; }
    public GameCore.TbGSingleton TbGSingleton {get; }
    public GameActor.TbAdventurer TbAdventurer {get; }
    public GameActor.TbClass TbClass {get; }
    public GameActor.TbSubrace TbSubrace {get; }
    public GameActor.TbItem TbItem {get; }
    public GameActor.TbWeaponBase TbWeaponBase {get; }
    public GameActor.TbAbility TbAbility {get; }
    public GameActor.TbPreset TbPreset {get; }
    public GameCombat.TbCampaign TbCampaign {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbAudio = new TbAudio(loader("tbaudio"));
        TbGSingleton = new GameCore.TbGSingleton(loader("gamecore_tbgsingleton"));
        TbAdventurer = new GameActor.TbAdventurer(loader("gameactor_tbadventurer"));
        TbClass = new GameActor.TbClass(loader("gameactor_tbclass"));
        TbSubrace = new GameActor.TbSubrace(loader("gameactor_tbsubrace"));
        TbItem = new GameActor.TbItem(loader("gameactor_tbitem"));
        TbWeaponBase = new GameActor.TbWeaponBase(loader("gameactor_tbweaponbase"));
        TbAbility = new GameActor.TbAbility(loader("gameactor_tbability"));
        TbPreset = new GameActor.TbPreset(loader("gameactor_tbpreset"));
        TbCampaign = new GameCombat.TbCampaign(loader("gamecombat_tbcampaign"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbAudio.ResolveRef(this);
        TbGSingleton.ResolveRef(this);
        TbAdventurer.ResolveRef(this);
        TbClass.ResolveRef(this);
        TbSubrace.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbWeaponBase.ResolveRef(this);
        TbAbility.ResolveRef(this);
        TbPreset.ResolveRef(this);
        TbCampaign.ResolveRef(this);
    }
}

}
