
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public partial class TbAudio
{

     private readonly Audio _data;

     public Audio Data => _data;

    public TbAudio(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = Audio.DeserializeAudio(_buf);
    }


    /// <summary>
    /// 按钮_悬停
    /// </summary>
     public string EnterBtn => _data.EnterBtn;
    /// <summary>
    /// 按钮_点击
    /// </summary>
     public string ClickBtn => _data.ClickBtn;
    /// <summary>
    /// 切换_悬停
    /// </summary>
     public string EnterTgl => _data.EnterTgl;
    /// <summary>
    /// 切换_点击
    /// </summary>
     public string ClickTgl => _data.ClickTgl;
    /// <summary>
    /// 进度条_拖拽_测试音乐
    /// </summary>
     public string DragBarMusic => _data.DragBarMusic;
    /// <summary>
    /// 进度条_拖拽_测试音效
    /// </summary>
     public string DragBarSfx => _data.DragBarSfx;
    /// <summary>
    /// 主菜单_背景乐
    /// </summary>
     public string MainMenuBgm => _data.MainMenuBgm;
    /// <summary>
    /// 游戏_背景乐
    /// </summary>
     public string GameBgm => _data.GameBgm;
    /// <summary>
    /// 弹窗_弹出
    /// </summary>
     public string PopOut => _data.PopOut;
    /// <summary>
    /// 弹窗_移动
    /// </summary>
     public string PopMove => _data.PopMove;
    /// <summary>
    /// 弹窗_隐藏
    /// </summary>
     public string PopHide => _data.PopHide;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

