
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Combat
{
public sealed partial class Campaign : Luban.BeanBase
{
    public Campaign(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Squads = new System.Collections.Generic.Dictionary<string, Combat.SquadStance[]>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { string _k0;  _k0 = _buf.ReadString(); Combat.SquadStance[] _v0;  {int __n1 = _buf.ReadSize(); _v0 = new Combat.SquadStance[__n1];for(var __index1 = 0 ; __index1 < __n1 ; __index1++) { Combat.SquadStance __e1;__e1 = global::Game.Config.Combat.SquadStance.DeserializeSquadStance(_buf); _v0[__index1] = __e1;}}     Squads.Add(_k0, _v0);}}
    }

    public static Campaign DeserializeCampaign(ByteBuf _buf)
    {
        return new Combat.Campaign(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 军队名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 小队名称
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, Combat.SquadStance[]> Squads;
   
    public const int __ID__ = -1356815670;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "squads:" + Luban.StringUtil.CollectionToString(Squads) + ","
        + "}";
    }
}
}

