
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Combat
{
public partial class TbCampaign
{
    private readonly System.Collections.Generic.Dictionary<int, Combat.CampaignCfg> _dataMap;
    private readonly System.Collections.Generic.List<Combat.CampaignCfg> _dataList;
    
    public TbCampaign(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Combat.CampaignCfg>();
        _dataList = new System.Collections.Generic.List<Combat.CampaignCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Combat.CampaignCfg _v;
            _v = Combat.CampaignCfg.DeserializeCampaignCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Combat.CampaignCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Combat.CampaignCfg> DataList => _dataList;

    public Combat.CampaignCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Combat.CampaignCfg Get(int key) => _dataMap[key];
    public Combat.CampaignCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

