
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Combat
{
/// <summary>
/// 战术地图瓦片-8
/// </summary>
public partial class TbTroopBfTile
{
    private readonly System.Collections.Generic.Dictionary<int, Combat.TroopBfTile> _dataMap;
    private readonly System.Collections.Generic.List<Combat.TroopBfTile> _dataList;
    
    public TbTroopBfTile(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Combat.TroopBfTile>(n);
        _dataList = new System.Collections.Generic.List<Combat.TroopBfTile>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Combat.TroopBfTile _v;
            _v = global::Game.Config.Combat.TroopBfTile.DeserializeTroopBfTile(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Combat.TroopBfTile> DataMap => _dataMap;
    public System.Collections.Generic.List<Combat.TroopBfTile> DataList => _dataList;

    public Combat.TroopBfTile GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Combat.TroopBfTile Get(int key) => _dataMap[key];
    public Combat.TroopBfTile this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

