
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Combat
{
public sealed partial class TroopBfTile : Luban.BeanBase
{
    public TroopBfTile(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Cost = _buf.ReadInt();
        Asset = _buf.ReadString();
    }

    public static TroopBfTile DeserializeTroopBfTile(ByteBuf _buf)
    {
        return new Combat.TroopBfTile(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 移动力花费
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 资源名称
    /// </summary>
    public readonly string Asset;
   
    public const int __ID__ = 2054171402;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "cost:" + Cost + ","
        + "asset:" + Asset + ","
        + "}";
    }
}
}

