
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameActor
{
/// <summary>
/// 能力值
/// </summary>
public sealed partial class AbilityScore : Luban.BeanBase
{
    public AbilityScore(ByteBuf _buf) 
    {
        Strength = _buf.ReadInt();
        Dexterity = _buf.ReadInt();
        Constitution = _buf.ReadInt();
        Intelligent = _buf.ReadInt();
        Wisdom = _buf.ReadInt();
        Charisma = _buf.ReadInt();
    }

    public static AbilityScore DeserializeAbilityScore(ByteBuf _buf)
    {
        return new GameActor.AbilityScore(_buf);
    }

    /// <summary>
    /// 力量
    /// </summary>
    public readonly int Strength;
    /// <summary>
    /// 敏捷
    /// </summary>
    public readonly int Dexterity;
    /// <summary>
    /// 体质
    /// </summary>
    public readonly int Constitution;
    /// <summary>
    /// 智力
    /// </summary>
    public readonly int Intelligent;
    /// <summary>
    /// 感知
    /// </summary>
    public readonly int Wisdom;
    /// <summary>
    /// 魅力
    /// </summary>
    public readonly int Charisma;
   
    public const int __ID__ = -1442772301;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "strength:" + Strength + ","
        + "dexterity:" + Dexterity + ","
        + "constitution:" + Constitution + ","
        + "intelligent:" + Intelligent + ","
        + "wisdom:" + Wisdom + ","
        + "charisma:" + Charisma + ","
        + "}";
    }
}

}

