
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameActor
{
public sealed partial class AdventurerCfg : Luban.BeanBase
{
    public AdventurerCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Subrace = _buf.ReadInt();
        Subrace_Ref = null;
        Level = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Clasz = new System.Collections.Generic.Dictionary<GameActor.EmClass, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { GameActor.EmClass _k0;  _k0 = (GameActor.EmClass)_buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     Clasz.Add(_k0, _v0);}}
        ExpOnKilled = _buf.ReadInt();
        MaxHp = GameActor.MaxHp.DeserializeMaxHp(_buf);
        AttributePreset = GameActor.AttributePreset.DeserializeAttributePreset(_buf);
        ItemPreset1 = GameActor.ActorItemPreset.DeserializeActorItemPreset(_buf);
        ItemPreset2 = GameActor.ActorItemPreset.DeserializeActorItemPreset(_buf);
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);KnapsackItems = new System.Collections.Generic.Dictionary<int, float>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); float _v0;  _v0 = _buf.ReadFloat();     KnapsackItems.Add(_k0, _v0);}}
    }

    public static AdventurerCfg DeserializeAdventurerCfg(ByteBuf _buf)
    {
        return new GameActor.AdventurerCfg(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 亚种
    /// </summary>
    public readonly int Subrace;
    public GameActor.SubraceCfg Subrace_Ref;
    /// <summary>
    /// 角色等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 职业
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<GameActor.EmClass, int> Clasz;
    /// <summary>
    /// 击杀经验
    /// </summary>
    public readonly int ExpOnKilled;
    /// <summary>
    /// 生命值类型
    /// </summary>
    public readonly GameActor.MaxHp MaxHp;
    /// <summary>
    /// 力量
    /// </summary>
    public readonly GameActor.AttributePreset AttributePreset;
    /// <summary>
    /// 主手装备
    /// </summary>
    public readonly GameActor.ActorItemPreset ItemPreset1;
    /// <summary>
    /// 主手装备
    /// </summary>
    public readonly GameActor.ActorItemPreset ItemPreset2;
    /// <summary>
    /// 道具id
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, float> KnapsackItems;
   
    public const int __ID__ = -841029673;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Subrace_Ref = tables.TbSubrace.GetOrDefault(Subrace);
        MaxHp?.ResolveRef(tables);
        AttributePreset?.ResolveRef(tables);
        ItemPreset1?.ResolveRef(tables);
        ItemPreset2?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "subrace:" + Subrace + ","
        + "level:" + Level + ","
        + "clasz:" + Luban.StringUtil.CollectionToString(Clasz) + ","
        + "expOnKilled:" + ExpOnKilled + ","
        + "maxHp:" + MaxHp + ","
        + "attributePreset:" + AttributePreset + ","
        + "itemPreset1:" + ItemPreset1 + ","
        + "itemPreset2:" + ItemPreset2 + ","
        + "knapsackItems:" + Luban.StringUtil.CollectionToString(KnapsackItems) + ","
        + "}";
    }
}

}

