
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.GameActor
{ 
    /// <summary>
    /// 职业
    /// </summary>
    public enum EmClass
    {
        /// <summary>
        /// 野蛮人
        /// </summary>
        Barbarian = 20001,
        /// <summary>
        /// 吟游诗人
        /// </summary>
        Bard = 20002,
        /// <summary>
        /// 牧师
        /// </summary>
        Cleric = 20003,
        /// <summary>
        /// 德鲁伊
        /// </summary>
        Druid = 20004,
        /// <summary>
        /// 战士
        /// </summary>
        Fighter = 20005,
        /// <summary>
        /// 武僧
        /// </summary>
        Monk = 20006,
        /// <summary>
        /// 圣武士
        /// </summary>
        Paladin = 20007,
        /// <summary>
        /// 游侠
        /// </summary>
        Ranger = 20008,
        /// <summary>
        /// 游荡者
        /// </summary>
        Rogue = 20009,
        /// <summary>
        /// 术士
        /// </summary>
        Sorcerer = 20010,
        /// <summary>
        /// 邪术师
        /// </summary>
        Warlock = 20011,
        /// <summary>
        /// 法师
        /// </summary>
        Wizard = 20012,
    }

} 

