
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.GameActor
{ 
    /// <summary>
    /// 基础武器
    /// </summary>
    [System.Flags]
    public enum EmEquipType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 无甲
        /// </summary>
        NoArmour = 1,
        /// <summary>
        /// 轻甲
        /// </summary>
        LightArmour = 2,
        /// <summary>
        /// 中甲
        /// </summary>
        MediumArmour = 4,
        /// <summary>
        /// 重甲
        /// </summary>
        HeavyArmour = 8,
        /// <summary>
        /// 盾牌
        /// </summary>
        Shield = 16,
        /// <summary>
        /// 短棒
        /// </summary>
        Club = 32,
        /// <summary>
        /// 匕首
        /// </summary>
        Dagger = 64,
        /// <summary>
        /// 巨棒
        /// </summary>
        Greatclub = 128,
        /// <summary>
        /// 手斧
        /// </summary>
        Handaxe = 256,
        /// <summary>
        /// 标枪
        /// </summary>
        Javelin = 512,
        /// <summary>
        /// 长棍
        /// </summary>
        Quarterstaff = 1024,
        /// <summary>
        /// 镰刀
        /// </summary>
        Sickle = 2048,
        /// <summary>
        /// 矛
        /// </summary>
        Spear = 4096,
        /// <summary>
        /// 轻弩
        /// </summary>
        LightCrossbow = 8192,
        /// <summary>
        /// 飞镖
        /// </summary>
        Dart = 16384,
        /// <summary>
        /// 短弓
        /// </summary>
        Shortbow = 32768,
        /// <summary>
        /// 战斧
        /// </summary>
        Battleaxe = 65536,
        /// <summary>
        /// 链枷
        /// </summary>
        Flail = 131072,
        /// <summary>
        /// 巨斧
        /// </summary>
        Greataxe = 262144,
        /// <summary>
        /// 巨剑
        /// </summary>
        Greatsword = 524288,
        /// <summary>
        /// 长剑
        /// </summary>
        Longsword = 1048576,
        /// <summary>
        /// 巨锤
        /// </summary>
        Maul = 2097152,
        /// <summary>
        /// 长矛
        /// </summary>
        Pike = 4194304,
        /// <summary>
        /// 刺剑
        /// </summary>
        Rapier = 8388608,
        /// <summary>
        /// 弯刀
        /// </summary>
        Scimiar = 16777216,
        /// <summary>
        /// 短剑
        /// </summary>
        ShortSword = 33554432,
        /// <summary>
        /// 战锤
        /// </summary>
        Warhammer = 67108864,
        /// <summary>
        /// 手弩
        /// </summary>
        HandCrossbow = 134217728,
        /// <summary>
        /// 重弩
        /// </summary>
        HeavyCrossbow = 268435456,
        /// <summary>
        /// 长弓
        /// </summary>
        Longbow = 536870912,
        /// <summary>
        /// 所有护甲
        /// </summary>
        AllArmour = NoArmour|LightArmour|MediumArmour|HeavyArmour,
        /// <summary>
        /// 简易近战
        /// </summary>
        SimpleMelee = Club|Dagger|Greatclub|Handaxe|Javelin|Quarterstaff|Sickle|Spear,
        /// <summary>
        /// 简易远程
        /// </summary>
        SimpleRanged = LightCrossbow|Dart|Shortbow,
        /// <summary>
        /// 军用近战
        /// </summary>
        MartialMelee = Battleaxe|Flail|Greataxe|Greatsword|Longsword|Maul|Pike|Rapier|Scimiar|ShortSword|Warhammer,
        /// <summary>
        /// 军用远程
        /// </summary>
        MartialRanged = HandCrossbow|HeavyCrossbow|Longbow,
        /// <summary>
        /// 简易武器
        /// </summary>
        Simple = SimpleMelee|SimpleRanged,
        /// <summary>
        /// 军用武器
        /// </summary>
        Martial = MartialMelee|MartialRanged,
    }

} 

