
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.GameActor
{ 
    /// <summary>
    /// 种族
    /// </summary>
    public enum EmRace
    {
        /// <summary>
        /// 人类
        /// </summary>
        Human = 1,
        /// <summary>
        /// 矮人
        /// </summary>
        Dwarf = 2,
        /// <summary>
        /// 精灵
        /// </summary>
        Elf = 3,
        /// <summary>
        /// 半身人
        /// </summary>
        Halfling = 4,
        /// <summary>
        /// 侏儒
        /// </summary>
        Gnome = 5,
        /// <summary>
        /// 半精灵
        /// </summary>
        HalfElf = 6,
        /// <summary>
        /// 龙裔
        /// </summary>
        Dragonborn = 7,
        /// <summary>
        /// 半兽人
        /// </summary>
        HalfOre = 8,
        /// <summary>
        /// 提夫林
        /// </summary>
        Tiefling = 9,
        /// <summary>
        /// 地精
        /// </summary>
        Goblin = 10,
    }

} 

