
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameActor
{
/// <summary>
/// 道具信息
/// </summary>
public abstract partial class ItemInfo : Luban.BeanBase
{
    public ItemInfo(ByteBuf _buf) 
    {
    }

    public static ItemInfo DeserializeItemInfo(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case GameActor.EmptyInfo.__ID__: return new GameActor.EmptyInfo(_buf);
            case GameActor.WeaponInfo.__ID__: return new GameActor.WeaponInfo(_buf);
            case GameActor.NArmourInfo.__ID__: return new GameActor.NArmourInfo(_buf);
            case GameActor.MArmourInfo.__ID__: return new GameActor.MArmourInfo(_buf);
            case GameActor.LArmourInfo.__ID__: return new GameActor.LArmourInfo(_buf);
            case GameActor.HArmourInfo.__ID__: return new GameActor.HArmourInfo(_buf);
            case GameActor.ShieldInfo.__ID__: return new GameActor.ShieldInfo(_buf);
            case GameActor.ArtifactInfo.__ID__: return new GameActor.ArtifactInfo(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

