
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameActor
{
/// <summary>
/// 中甲信息
/// </summary>
public sealed partial class LArmourInfo : GameActor.ItemInfo
{
    public LArmourInfo(ByteBuf _buf)  : base(_buf) 
    {
        ArmourClass = _buf.ReadInt();
        Limited = _buf.ReadInt();
    }

    public static LArmourInfo DeserializeLArmourInfo(ByteBuf _buf)
    {
        return new GameActor.LArmourInfo(_buf);
    }

    /// <summary>
    /// 护甲等级
    /// </summary>
    public readonly int ArmourClass;
    /// <summary>
    /// 调整值上限
    /// </summary>
    public readonly int Limited;
   
    public const int __ID__ = -1861888705;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "armourClass:" + ArmourClass + ","
        + "limited:" + Limited + ","
        + "}";
    }
}

}

