
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameActor
{
/// <summary>
/// 骰子生命值
/// </summary>
public sealed partial class MaxHpFromDice : GameActor.MaxHp
{
    public MaxHpFromDice(ByteBuf _buf)  : base(_buf) 
    {
        Dice = GameCore.Dice.DeserializeDice(_buf);
        BaseNumber = _buf.ReadInt();
    }

    public static MaxHpFromDice DeserializeMaxHpFromDice(ByteBuf _buf)
    {
        return new GameActor.MaxHpFromDice(_buf);
    }

    /// <summary>
    /// 骰子
    /// </summary>
    public readonly GameCore.Dice Dice;
    /// <summary>
    /// 基础值
    /// </summary>
    public readonly int BaseNumber;
   
    public const int __ID__ = 1023659602;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Dice?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "dice:" + Dice + ","
        + "baseNumber:" + BaseNumber + ","
        + "}";
    }
}

}

