
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameActor
{
/// <summary>
/// 最大生命值
/// </summary>
public abstract partial class MaxHp : Luban.BeanBase
{
    public MaxHp(ByteBuf _buf) 
    {
    }

    public static MaxHp DeserializeMaxHp(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case GameActor.MaxHpFromDice.__ID__: return new GameActor.MaxHpFromDice(_buf);
            case GameActor.MaxHpFromClass.__ID__: return new GameActor.MaxHpFromClass(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

