
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameActor
{
/// <summary>
/// 无甲信息
/// </summary>
public sealed partial class NArmourInfo : GameActor.ItemInfo
{
    public NArmourInfo(ByteBuf _buf)  : base(_buf) 
    {
    }

    public static NArmourInfo DeserializeNArmourInfo(ByteBuf _buf)
    {
        return new GameActor.NArmourInfo(_buf);
    }

   
    public const int __ID__ = -1160824127;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

