
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameActor
{
public partial class TbAbility
{
    private readonly System.Collections.Generic.Dictionary<int, GameActor.AbilityCfg> _dataMap;
    private readonly System.Collections.Generic.List<GameActor.AbilityCfg> _dataList;
    
    public TbAbility(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameActor.AbilityCfg>();
        _dataList = new System.Collections.Generic.List<GameActor.AbilityCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameActor.AbilityCfg _v;
            _v = GameActor.AbilityCfg.DeserializeAbilityCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameActor.AbilityCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<GameActor.AbilityCfg> DataList => _dataList;

    public GameActor.AbilityCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameActor.AbilityCfg Get(int key) => _dataMap[key];
    public GameActor.AbilityCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

