
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameActor
{
public partial class TbAdventurer
{
    private readonly System.Collections.Generic.Dictionary<int, GameActor.AdventurerCfg> _dataMap;
    private readonly System.Collections.Generic.List<GameActor.AdventurerCfg> _dataList;
    
    public TbAdventurer(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameActor.AdventurerCfg>();
        _dataList = new System.Collections.Generic.List<GameActor.AdventurerCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameActor.AdventurerCfg _v;
            _v = GameActor.AdventurerCfg.DeserializeAdventurerCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameActor.AdventurerCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<GameActor.AdventurerCfg> DataList => _dataList;

    public GameActor.AdventurerCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameActor.AdventurerCfg Get(int key) => _dataMap[key];
    public GameActor.AdventurerCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

