
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameActor
{
public partial class TbClass
{
    private readonly System.Collections.Generic.Dictionary<GameActor.EmClass, GameActor.ClassCfg> _dataMap;
    private readonly System.Collections.Generic.List<GameActor.ClassCfg> _dataList;
    
    public TbClass(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<GameActor.EmClass, GameActor.ClassCfg>();
        _dataList = new System.Collections.Generic.List<GameActor.ClassCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameActor.ClassCfg _v;
            _v = GameActor.ClassCfg.DeserializeClassCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<GameActor.EmClass, GameActor.ClassCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<GameActor.ClassCfg> DataList => _dataList;

    public GameActor.ClassCfg GetOrDefault(GameActor.EmClass key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameActor.ClassCfg Get(GameActor.EmClass key) => _dataMap[key];
    public GameActor.ClassCfg this[GameActor.EmClass key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

