
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.GameActor
{
public partial class TbPreset
{
    private readonly System.Collections.Generic.Dictionary<int, GameActor.PresetCfg> _dataMap;
    private readonly System.Collections.Generic.List<GameActor.PresetCfg> _dataList;
    
    public TbPreset(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameActor.PresetCfg>();
        _dataList = new System.Collections.Generic.List<GameActor.PresetCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameActor.PresetCfg _v;
            _v = GameActor.PresetCfg.DeserializePresetCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameActor.PresetCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<GameActor.PresetCfg> DataList => _dataList;

    public GameActor.PresetCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameActor.PresetCfg Get(int key) => _dataMap[key];
    public GameActor.PresetCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

