
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config.GameActor
{
public sealed partial class WeaponBaseCfg : Luban.BeanBase
{
    public WeaponBaseCfg(ByteBuf _buf) 
    {
        Id = (GameActor.EmEquipType)_buf.ReadInt();
        Name = _buf.ReadString();
        DamgeDice = GameActor.Damage.DeserializeDamage(_buf);
        AbilityAddtion = (GameActor.EmAbilityScore)_buf.ReadInt();
        Range = _buf.ReadInt();
        Position = (GameActor.EmWeaponType)_buf.ReadInt();
    }

    public static WeaponBaseCfg DeserializeWeaponBaseCfg(ByteBuf _buf)
    {
        return new GameActor.WeaponBaseCfg(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly GameActor.EmEquipType Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly GameActor.Damage DamgeDice;
    /// <summary>
    /// 调整值加成
    /// </summary>
    public readonly GameActor.EmAbilityScore AbilityAddtion;
    /// <summary>
    /// 范围
    /// </summary>
    public readonly int Range;
    /// <summary>
    /// 位置
    /// </summary>
    public readonly GameActor.EmWeaponType Position;
   
    public const int __ID__ = 471130188;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        DamgeDice?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "damgeDice:" + DamgeDice + ","
        + "abilityAddtion:" + AbilityAddtion + ","
        + "range:" + Range + ","
        + "position:" + Position + ","
        + "}";
    }
}

}

