
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Game
{
/// <summary>
/// 骰子
/// </summary>
public sealed partial class Dice : Luban.BeanBase
{
    public Dice(ByteBuf _buf) 
    {
        Amount = _buf.ReadInt();
        DiceFaces = _buf.ReadInt();
    }

    public static Dice DeserializeDice(ByteBuf _buf)
    {
        return new Game.Dice(_buf);
    }

    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Amount;
    /// <summary>
    /// 骰子面数
    /// </summary>
    public readonly int DiceFaces;
   
    public const int __ID__ = -1336527837;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "amount:" + Amount + ","
        + "diceFaces:" + DiceFaces + ","
        + "}";
    }
}
}

