
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Game
{
public sealed partial class Global : Luban.BeanBase
{
    public Global(ByteBuf _buf) 
    {
        MaxLevel = _buf.ReadInt();
    }

    public static Global DeserializeGlobal(ByteBuf _buf)
    {
        return new Game.Global(_buf);
    }

    /// <summary>
    /// 最高等级
    /// </summary>
    public readonly int MaxLevel;
   
    public const int __ID__ = -119014113;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "maxLevel:" + MaxLevel + ","
        + "}";
    }
}
}

