
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Game
{
public partial class TbDefine
{

     private readonly Game.Define _data;

     public Game.Define Data => _data;

    public TbDefine(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::Game.Config.Game.Define.DeserializeDefine(_buf);
    }


    /// <summary>
    /// 战役地图长
    /// </summary>
     public int BattleMapLength => _data.BattleMapLength;
    /// <summary>
    /// 战役地图宽
    /// </summary>
     public int BattleMapWidth => _data.BattleMapWidth;
    /// <summary>
    /// 战斗倒地回合计数上限
    /// </summary>
     public int BattleDownRoundCountMax => _data.BattleDownRoundCountMax;
    /// <summary>
    /// 奇物栏位数量上限
    /// </summary>
     public int ArtifactField => _data.ArtifactField;
    /// <summary>
    /// 默认能力
    /// </summary>
     public int[] DefaultAbilities => _data.DefaultAbilities;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

