
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Game
{
public partial class TbGlobal
{

     private readonly Game.Global _data;

     public Game.Global Data => _data;

    public TbGlobal(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::Game.Config.Game.Global.DeserializeGlobal(_buf);
    }


    /// <summary>
    /// 最高等级
    /// </summary>
     public int MaxLevel => _data.MaxLevel;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

