
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 预设角色道具
/// </summary>
public sealed partial class ActorItemPreset : Luban.BeanBase
{
    public ActorItemPreset(ByteBuf _buf) 
    {
        MainHand = _buf.ReadInt();
        MainHand_Ref = null;
        OffHand = _buf.ReadInt();
        OffHand_Ref = null;
        Body = _buf.ReadInt();
        Body_Ref = null;
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Artifacts = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Artifacts[__index0] = __e0;}}
    }

    public static ActorItemPreset DeserializeActorItemPreset(ByteBuf _buf)
    {
        return new Character.ActorItemPreset(_buf);
    }

    /// <summary>
    /// 主手
    /// </summary>
    public readonly int MainHand;
    public Character.ItemCfg MainHand_Ref;
    /// <summary>
    /// 副手
    /// </summary>
    public readonly int OffHand;
    public Character.ItemCfg OffHand_Ref;
    /// <summary>
    /// 甲
    /// </summary>
    public readonly int Body;
    public Character.ItemCfg Body_Ref;
    /// <summary>
    /// 奇物
    /// </summary>
    public readonly int[] Artifacts;
    public Character.ItemCfg[] Artifacts_Ref;
   
    public const int __ID__ = 1397360290;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        MainHand_Ref = tables.TbItem.GetOrDefault(MainHand);
        OffHand_Ref = tables.TbItem.GetOrDefault(OffHand);
        Body_Ref = tables.TbItem.GetOrDefault(Body);
        Artifacts_Ref = new Character.ItemCfg[Artifacts.Length];
        for (int _i = 0; _i < Artifacts.Length; _i++) { Artifacts_Ref[_i] = tables.TbItem.GetOrDefault(Artifacts[_i]); }

    }

    public override string ToString()
    {
        return "{ "
        + "mainHand:" + MainHand + ","
        + "offHand:" + OffHand + ","
        + "body:" + Body + ","
        + "artifacts:" + Luban.StringUtil.CollectionToString(Artifacts) + ","
        + "}";
    }
}

}

