
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 奇物信息
/// </summary>
public sealed partial class ArtifactInfo : Character.ItemInfo
{
    public ArtifactInfo(ByteBuf _buf)  : base(_buf) 
    {
    }

    public static ArtifactInfo DeserializeArtifactInfo(ByteBuf _buf)
    {
        return new Character.ArtifactInfo(_buf);
    }

   
    public const int __ID__ = 1442463877;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

