
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
public sealed partial class Asset : Luban.BeanBase
{
    public Asset(ByteBuf _buf) 
    {
        Prefab = _buf.ReadString();
        SquadPrefab = _buf.ReadString();
        Icon = _buf.ReadString();
    }

    public static Asset DeserializeAsset(ByteBuf _buf)
    {
        return new Character.Asset(_buf);
    }

    /// <summary>
    /// 预制体
    /// </summary>
    public readonly string Prefab;
    /// <summary>
    /// 小队预制体
    /// </summary>
    public readonly string SquadPrefab;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = 33462187;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "prefab:" + Prefab + ","
        + "squadPrefab:" + SquadPrefab + ","
        + "icon:" + Icon + ","
        + "}";
    }
}
}

