
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 角色预设
/// </summary>
public sealed partial class AttributePreset : Luban.BeanBase
{
    public AttributePreset(ByteBuf _buf) 
    {
        AbilityScores = Character.AbilityScore.DeserializeAbilityScore(_buf);
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Resistance = new System.Collections.Generic.Dictionary<Character.EmDamageType, float>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { Character.EmDamageType _k0;  _k0 = (Character.EmDamageType)_buf.ReadInt(); float _v0;  _v0 = _buf.ReadFloat();     Resistance.Add(_k0, _v0);}}
        ArmourClass = _buf.ReadInt();
        Movement = _buf.ReadInt();
        Initiative = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Abilities = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Abilities[__index0] = __e0;}}
    }

    public static AttributePreset DeserializeAttributePreset(ByteBuf _buf)
    {
        return new Character.AttributePreset(_buf);
    }

    /// <summary>
    /// 能力值
    /// </summary>
    public readonly Character.AbilityScore AbilityScores;
    /// <summary>
    /// 伤害抗性
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<Character.EmDamageType, float> Resistance;
    /// <summary>
    /// 护甲等级
    /// </summary>
    public readonly int ArmourClass;
    /// <summary>
    /// 移动力
    /// </summary>
    public readonly int Movement;
    /// <summary>
    /// 先攻
    /// </summary>
    public readonly int Initiative;
    /// <summary>
    /// 能力
    /// </summary>
    public readonly int[] Abilities;
   
    public const int __ID__ = 209671062;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        AbilityScores?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "abilityScores:" + AbilityScores + ","
        + "resistance:" + Luban.StringUtil.CollectionToString(Resistance) + ","
        + "armourClass:" + ArmourClass + ","
        + "movement:" + Movement + ","
        + "initiative:" + Initiative + ","
        + "abilities:" + Luban.StringUtil.CollectionToString(Abilities) + ","
        + "}";
    }
}

}

