
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
public sealed partial class ClassCfg : Luban.BeanBase
{
    public ClassCfg(ByteBuf _buf) 
    {
        Id = (Character.EmClass)_buf.ReadInt();
        Name = _buf.ReadString();
    }

    public static ClassCfg DeserializeClassCfg(ByteBuf _buf)
    {
        return new Character.ClassCfg(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly Character.EmClass Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = 1505304881;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "}";
    }
}

}

