
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 伤害
/// </summary>
public sealed partial class Damage : Luban.BeanBase
{
    public Damage(ByteBuf _buf) 
    {
        Dice = global::Game.Config.Game.Dice.DeserializeDice(_buf);
        DamageType = (Character.EmDamageType)_buf.ReadInt();
    }

    public static Damage DeserializeDamage(ByteBuf _buf)
    {
        return new Character.Damage(_buf);
    }

    /// <summary>
    /// 数值
    /// </summary>
    public readonly Game.Dice Dice;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly Character.EmDamageType DamageType;
   
    public const int __ID__ = 1106408980;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Dice?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "dice:" + Dice + ","
        + "damageType:" + DamageType + ","
        + "}";
    }
}
}

