
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    /// <summary>
    /// 角色能力值
    /// </summary>
    public enum EmAbilityScore
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 力量
        /// </summary>
        Strength = 1,
        /// <summary>
        /// 敏捷
        /// </summary>
        Dexterity = 2,
        /// <summary>
        /// 体质
        /// </summary>
        Constitution = 3,
        /// <summary>
        /// 智力
        /// </summary>
        Intelligent = 4,
        /// <summary>
        /// 感知
        /// </summary>
        Wisdom = 5,
        /// <summary>
        /// 魅力
        /// </summary>
        Charisma = 6,
    }

} 

