
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    /// <summary>
    /// 角色体型
    /// </summary>
    public enum EmBodyType
    {
        /// <summary>
        /// 小型
        /// </summary>
        Small = 2,
        /// <summary>
        /// 中型
        /// </summary>
        Medium = 4,
        /// <summary>
        /// 大型
        /// </summary>
        Large = 9,
        /// <summary>
        /// 巨型
        /// </summary>
        Gargantuan = 36,
    }

} 

