
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    /// <summary>
    /// 生物类型
    /// </summary>
    [System.Flags]
    public enum EmCreatureType
    {
        /// <summary>
        /// 异怪
        /// </summary>
        Aberration = 1,
        /// <summary>
        /// 野兽
        /// </summary>
        Beast = 2,
        /// <summary>
        /// 天界生物
        /// </summary>
        Celestial = 4,
        /// <summary>
        /// 构造生物
        /// </summary>
        Constructs = 8,
        /// <summary>
        /// 龙类
        /// </summary>
        Dragons = 16,
        /// <summary>
        /// 元素生物
        /// </summary>
        Elementals = 32,
        /// <summary>
        /// 精类
        /// </summary>
        Fey = 64,
        /// <summary>
        /// 邪魔
        /// </summary>
        Fiends = 128,
        /// <summary>
        /// 巨人
        /// </summary>
        Giants = 256,
        /// <summary>
        /// 类人
        /// </summary>
        Humanoids = 512,
        /// <summary>
        /// 怪兽
        /// </summary>
        Monstrosities = 1024,
        /// <summary>
        /// 泥怪
        /// </summary>
        Oozes = 2048,
        /// <summary>
        /// 植物
        /// </summary>
        Plant = 4096,
        /// <summary>
        /// 不死生物
        /// </summary>
        Undead = 8192,
    }

} 

