
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    /// <summary>
    /// 伤害类型
    /// </summary>
    public enum EmDamageType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 强酸
        /// </summary>
        Acid = 1,
        /// <summary>
        /// 冰冻
        /// </summary>
        Cold = 2,
        /// <summary>
        /// 火焰
        /// </summary>
        Fire = 3,
        /// <summary>
        /// 闪电
        /// </summary>
        Lighting = 4,
        /// <summary>
        /// 毒素
        /// </summary>
        Poison = 5,
        /// <summary>
        /// 钝击
        /// </summary>
        Bludgeoning = 6,
        /// <summary>
        /// 穿刺
        /// </summary>
        Piercing = 7,
        /// <summary>
        /// 挥砍
        /// </summary>
        Slashing = 8,
    }

} 

