
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 空占位符
/// </summary>
public sealed partial class EmptyInfo : Character.ItemInfo
{
    public EmptyInfo(ByteBuf _buf)  : base(_buf) 
    {
    }

    public static EmptyInfo DeserializeEmptyInfo(ByteBuf _buf)
    {
        return new Character.EmptyInfo(_buf);
    }

   
    public const int __ID__ = -1990277418;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

