
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    /// <summary>
    /// 武器类型
    /// </summary>
    public enum EmWeaponType
    {
        /// <summary>
        /// 单手
        /// </summary>
        OneHand = 1,
        /// <summary>
        /// 双手
        /// </summary>
        TwoHand = 2,
    }

} 

