
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 重甲信息
/// </summary>
public sealed partial class HArmourInfo : Character.ItemInfo
{
    public HArmourInfo(ByteBuf _buf)  : base(_buf) 
    {
        ArmourClass = _buf.ReadInt();
        EquipNeed = _buf.ReadInt();
    }

    public static HArmourInfo DeserializeHArmourInfo(ByteBuf _buf)
    {
        return new Character.HArmourInfo(_buf);
    }

    /// <summary>
    /// 护甲等级
    /// </summary>
    public readonly int ArmourClass;
    /// <summary>
    /// 装备力量需求
    /// </summary>
    public readonly int EquipNeed;
   
    public const int __ID__ = -92678335;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "armourClass:" + ArmourClass + ","
        + "equipNeed:" + EquipNeed + ","
        + "}";
    }
}
}

