
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
public sealed partial class ItemCfg : Luban.BeanBase
{
    public ItemCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        TypeInfo = Character.ItemInfo.DeserializeItemInfo(_buf);
        Price = _buf.ReadInt();
        Description = _buf.ReadString();
    }

    public static ItemCfg DeserializeItemCfg(ByteBuf _buf)
    {
        return new Character.ItemCfg(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 装备信息
    /// </summary>
    public readonly Character.ItemInfo TypeInfo;
    /// <summary>
    /// 价格(cp)
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 文本描述
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = 618379852;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        TypeInfo?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "typeInfo:" + TypeInfo + ","
        + "price:" + Price + ","
        + "description:" + Description + ","
        + "}";
    }
}

}

