
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 道具信息
/// </summary>
public abstract partial class ItemInfo : Luban.BeanBase
{
    public ItemInfo(ByteBuf _buf) 
    {
    }

    public static ItemInfo DeserializeItemInfo(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Character.EmptyInfo.__ID__: return new Character.EmptyInfo(_buf);
            case Character.WeaponInfo.__ID__: return new Character.WeaponInfo(_buf);
            case Character.NArmourInfo.__ID__: return new Character.NArmourInfo(_buf);
            case Character.MArmourInfo.__ID__: return new Character.MArmourInfo(_buf);
            case Character.LArmourInfo.__ID__: return new Character.LArmourInfo(_buf);
            case Character.HArmourInfo.__ID__: return new Character.HArmourInfo(_buf);
            case Character.ShieldInfo.__ID__: return new Character.ShieldInfo(_buf);
            case Character.ArtifactInfo.__ID__: return new Character.ArtifactInfo(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

