
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 轻甲信息
/// </summary>
public sealed partial class MArmourInfo : Character.ItemInfo
{
    public MArmourInfo(ByteBuf _buf)  : base(_buf) 
    {
        ArmourClass = _buf.ReadInt();
    }

    public static MArmourInfo DeserializeMArmourInfo(ByteBuf _buf)
    {
        return new Character.MArmourInfo(_buf);
    }

    /// <summary>
    /// 护甲等级
    /// </summary>
    public readonly int ArmourClass;
   
    public const int __ID__ = -487500538;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "armourClass:" + ArmourClass + ","
        + "}";
    }
}
}

