
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 职业生命值
/// </summary>
public sealed partial class MaxHpFromClass : Character.MaxHp
{
    public MaxHpFromClass(ByteBuf _buf)  : base(_buf) 
    {
    }

    public static MaxHpFromClass DeserializeMaxHpFromClass(ByteBuf _buf)
    {
        return new Character.MaxHpFromClass(_buf);
    }

   
    public const int __ID__ = -1646917273;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

