
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
public sealed partial class Preset : Luban.BeanBase
{
    public Preset(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Subrace = _buf.ReadInt();
        Subrace_Ref = null;
        Level = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Clasz = new System.Collections.Generic.Dictionary<int, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     Clasz.Add(_k0, _v0);}}
        ExpOnKilled = _buf.ReadInt();
        MaxHp = global::Game.Config.Character.MaxHp.DeserializeMaxHp(_buf);
        AttributePreset = global::Game.Config.Character.AttributePreset.DeserializeAttributePreset(_buf);
        ItemPreset1 = global::Game.Config.Character.ItemPreset.DeserializeItemPreset(_buf);
        ItemPreset2 = global::Game.Config.Character.ItemPreset.DeserializeItemPreset(_buf);
    }

    public static Preset DeserializePreset(ByteBuf _buf)
    {
        return new Character.Preset(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 亚种
    /// </summary>
    public readonly int Subrace;
    public Character.Race Subrace_Ref;
    /// <summary>
    /// 角色等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 职业
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, int> Clasz;
    /// <summary>
    /// 击杀经验
    /// </summary>
    public readonly int ExpOnKilled;
    /// <summary>
    /// 生命值类型
    /// </summary>
    public readonly Character.MaxHp MaxHp;
    /// <summary>
    /// 力量
    /// </summary>
    public readonly Character.AttributePreset AttributePreset;
    /// <summary>
    /// 主手装备
    /// </summary>
    public readonly Character.ItemPreset ItemPreset1;
    /// <summary>
    /// 主手装备
    /// </summary>
    public readonly Character.ItemPreset ItemPreset2;
   
    public const int __ID__ = 1465437572;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Subrace_Ref = tables.TbRace.GetOrDefault(Subrace);
        MaxHp?.ResolveRef(tables);
        AttributePreset?.ResolveRef(tables);
        ItemPreset1?.ResolveRef(tables);
        ItemPreset2?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "subrace:" + Subrace + ","
        + "level:" + Level + ","
        + "clasz:" + Luban.StringUtil.CollectionToString(Clasz) + ","
        + "expOnKilled:" + ExpOnKilled + ","
        + "maxHp:" + MaxHp + ","
        + "attributePreset:" + AttributePreset + ","
        + "itemPreset1:" + ItemPreset1 + ","
        + "itemPreset2:" + ItemPreset2 + ","
        + "}";
    }
}
}

