
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
public sealed partial class Race : Luban.BeanBase
{
    public Race(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        MainRace = (Character.EmRace)_buf.ReadInt();
        CreatureType = (Character.EmCreatureType)_buf.ReadInt();
        BodyType = (Character.EmBodyType)_buf.ReadInt();
        Proficiency = (Character.EmEquipType)_buf.ReadInt();
        AttributePreset = global::Game.Config.Character.AttributePreset.DeserializeAttributePreset(_buf);
    }

    public static Race DeserializeRace(ByteBuf _buf)
    {
        return new Character.Race(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 种族
    /// </summary>
    public readonly Character.EmRace MainRace;
    /// <summary>
    /// 类别
    /// </summary>
    public readonly Character.EmCreatureType CreatureType;
    /// <summary>
    /// 体型
    /// </summary>
    public readonly Character.EmBodyType BodyType;
    /// <summary>
    /// 装备熟练
    /// </summary>
    public readonly Character.EmEquipType Proficiency;
    /// <summary>
    /// 力量
    /// </summary>
    public readonly Character.AttributePreset AttributePreset;
   
    public const int __ID__ = -691168586;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        AttributePreset?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "mainRace:" + MainRace + ","
        + "creatureType:" + CreatureType + ","
        + "bodyType:" + BodyType + ","
        + "proficiency:" + Proficiency + ","
        + "attributePreset:" + AttributePreset + ","
        + "}";
    }
}
}

