
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
public partial class TbAbility
{
    private readonly System.Collections.Generic.Dictionary<int, Character.AbilityCfg> _dataMap;
    private readonly System.Collections.Generic.List<Character.AbilityCfg> _dataList;
    
    public TbAbility(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Character.AbilityCfg>();
        _dataList = new System.Collections.Generic.List<Character.AbilityCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Character.AbilityCfg _v;
            _v = Character.AbilityCfg.DeserializeAbilityCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Character.AbilityCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.AbilityCfg> DataList => _dataList;

    public Character.AbilityCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Character.AbilityCfg Get(int key) => _dataMap[key];
    public Character.AbilityCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

