
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 能力-5
/// </summary>
public partial class TbAbility
{
    private readonly System.Collections.Generic.Dictionary<int, Character.Ability> _dataMap;
    private readonly System.Collections.Generic.List<Character.Ability> _dataList;
    
    public TbAbility(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Character.Ability>(n);
        _dataList = new System.Collections.Generic.List<Character.Ability>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Character.Ability _v;
            _v = global::Game.Config.Character.Ability.DeserializeAbility(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Character.Ability> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.Ability> DataList => _dataList;

    public Character.Ability GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Character.Ability Get(int key) => _dataMap[key];
    public Character.Ability this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

