
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 冒险者-1
/// </summary>
public partial class TbAdventurer
{
    private readonly System.Collections.Generic.Dictionary<int, Character.Adventurer> _dataMap;
    private readonly System.Collections.Generic.List<Character.Adventurer> _dataList;
    
    public TbAdventurer(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Character.Adventurer>(n);
        _dataList = new System.Collections.Generic.List<Character.Adventurer>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Character.Adventurer _v;
            _v = global::Game.Config.Character.Adventurer.DeserializeAdventurer(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Character.Adventurer> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.Adventurer> DataList => _dataList;

    public Character.Adventurer GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Character.Adventurer Get(int key) => _dataMap[key];
    public Character.Adventurer this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

