
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 奇物-8
/// </summary>
public partial class TbArtifact
{
    private readonly System.Collections.Generic.Dictionary<int, Character.Artifact> _dataMap;
    private readonly System.Collections.Generic.List<Character.Artifact> _dataList;
    
    public TbArtifact(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Character.Artifact>(n);
        _dataList = new System.Collections.Generic.List<Character.Artifact>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Character.Artifact _v;
            _v = global::Game.Config.Character.Artifact.DeserializeArtifact(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Character.Artifact> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.Artifact> DataList => _dataList;

    public Character.Artifact GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Character.Artifact Get(int key) => _dataMap[key];
    public Character.Artifact this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

