
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 职业-2
/// </summary>
public partial class TbClasz
{
    private readonly System.Collections.Generic.Dictionary<int, Character.Clasz> _dataMap;
    private readonly System.Collections.Generic.List<Character.Clasz> _dataList;
    
    public TbClasz(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Character.Clasz>(n);
        _dataList = new System.Collections.Generic.List<Character.Clasz>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Character.Clasz _v;
            _v = global::Game.Config.Character.Clasz.DeserializeClasz(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Character.Clasz> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.Clasz> DataList => _dataList;

    public Character.Clasz GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Character.Clasz Get(int key) => _dataMap[key];
    public Character.Clasz this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

