
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
public partial class TbItem
{
    private readonly System.Collections.Generic.Dictionary<int, Character.ItemCfg> _dataMap;
    private readonly System.Collections.Generic.List<Character.ItemCfg> _dataList;
    
    public TbItem(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Character.ItemCfg>();
        _dataList = new System.Collections.Generic.List<Character.ItemCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Character.ItemCfg _v;
            _v = Character.ItemCfg.DeserializeItemCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Character.ItemCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.ItemCfg> DataList => _dataList;

    public Character.ItemCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Character.ItemCfg Get(int key) => _dataMap[key];
    public Character.ItemCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

