
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 预设-6
/// </summary>
public partial class TbPreset
{
    private readonly System.Collections.Generic.Dictionary<int, Character.Preset> _dataMap;
    private readonly System.Collections.Generic.List<Character.Preset> _dataList;
    
    public TbPreset(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Character.Preset>(n);
        _dataList = new System.Collections.Generic.List<Character.Preset>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Character.Preset _v;
            _v = global::Game.Config.Character.Preset.DeserializePreset(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Character.Preset> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.Preset> DataList => _dataList;

    public Character.Preset GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Character.Preset Get(int key) => _dataMap[key];
    public Character.Preset this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

