
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 种族-3
/// </summary>
public partial class TbRace
{
    private readonly System.Collections.Generic.Dictionary<int, Character.Race> _dataMap;
    private readonly System.Collections.Generic.List<Character.Race> _dataList;
    
    public TbRace(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Character.Race>(n);
        _dataList = new System.Collections.Generic.List<Character.Race>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Character.Race _v;
            _v = global::Game.Config.Character.Race.DeserializeRace(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Character.Race> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.Race> DataList => _dataList;

    public Character.Race GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Character.Race Get(int key) => _dataMap[key];
    public Character.Race this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

