
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
public partial class TbWeaponBase
{
    private readonly System.Collections.Generic.Dictionary<Character.EmEquipType, Character.WeaponBaseCfg> _dataMap;
    private readonly System.Collections.Generic.List<Character.WeaponBaseCfg> _dataList;
    
    public TbWeaponBase(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<Character.EmEquipType, Character.WeaponBaseCfg>();
        _dataList = new System.Collections.Generic.List<Character.WeaponBaseCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Character.WeaponBaseCfg _v;
            _v = Character.WeaponBaseCfg.DeserializeWeaponBaseCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<Character.EmEquipType, Character.WeaponBaseCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.WeaponBaseCfg> DataList => _dataList;

    public Character.WeaponBaseCfg GetOrDefault(Character.EmEquipType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Character.WeaponBaseCfg Get(Character.EmEquipType key) => _dataMap[key];
    public Character.WeaponBaseCfg this[Character.EmEquipType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

