
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
public partial class TbWeaponType
{
    private readonly System.Collections.Generic.Dictionary<Character.EmEquipType, Character.WeaponType> _dataMap;
    private readonly System.Collections.Generic.List<Character.WeaponType> _dataList;
    
    public TbWeaponType(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<Character.EmEquipType, Character.WeaponType>(n);
        _dataList = new System.Collections.Generic.List<Character.WeaponType>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Character.WeaponType _v;
            _v = global::Game.Config.Character.WeaponType.DeserializeWeaponType(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<Character.EmEquipType, Character.WeaponType> DataMap => _dataMap;
    public System.Collections.Generic.List<Character.WeaponType> DataList => _dataList;

    public Character.WeaponType GetOrDefault(Character.EmEquipType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Character.WeaponType Get(Character.EmEquipType key) => _dataMap[key];
    public Character.WeaponType this[Character.EmEquipType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

