
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
/// <summary>
/// 武器信息
/// </summary>
public sealed partial class WeaponInfo : Character.ItemInfo
{
    public WeaponInfo(ByteBuf _buf)  : base(_buf) 
    {
        Type = (Character.EmEquipType)_buf.ReadInt();
    }

    public static WeaponInfo DeserializeWeaponInfo(ByteBuf _buf)
    {
        return new Character.WeaponInfo(_buf);
    }

    /// <summary>
    /// 基础类型
    /// </summary>
    public readonly Character.EmEquipType Type;
   
    public const int __ID__ = 882785551;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "}";
    }
}

}

