
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Character
{
public sealed partial class WeaponType : Luban.BeanBase
{
    public WeaponType(ByteBuf _buf) 
    {
        Id = (Character.EmEquipType)_buf.ReadInt();
        Name = _buf.ReadString();
        DamgeDice = global::Game.Config.Character.Damage.DeserializeDamage(_buf);
        AbilityAddtion = (Character.EmAbilityScore)_buf.ReadInt();
        Range = _buf.ReadInt();
        Position = (Character.EmWeaponType)_buf.ReadInt();
    }

    public static WeaponType DeserializeWeaponType(ByteBuf _buf)
    {
        return new Character.WeaponType(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly Character.EmEquipType Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly Character.Damage DamgeDice;
    /// <summary>
    /// 调整值加成
    /// </summary>
    public readonly Character.EmAbilityScore AbilityAddtion;
    /// <summary>
    /// 范围
    /// </summary>
    public readonly int Range;
    /// <summary>
    /// 位置
    /// </summary>
    public readonly Character.EmWeaponType Position;
   
    public const int __ID__ = 883124123;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        DamgeDice?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "damgeDice:" + DamgeDice + ","
        + "abilityAddtion:" + AbilityAddtion + ","
        + "range:" + Range + ","
        + "position:" + Position + ","
        + "}";
    }
}
}

