
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Global
{
public partial class TbGSingleton
{

     private readonly Global.GameSingletonCfg _data;

     public Global.GameSingletonCfg Data => _data;

    public TbGSingleton(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = Global.GameSingletonCfg.DeserializeGameSingletonCfg(_buf);
    }


    /// <summary>
    /// 战役地图边长
    /// </summary>
     public int BattleMapLength => _data.BattleMapLength;
    /// <summary>
    /// 战斗倒地回合计数上限
    /// </summary>
     public int BattleDownRoundCountMax => _data.BattleDownRoundCountMax;
    /// <summary>
    /// 奇物栏位数量上限
    /// </summary>
     public int ArtifactField => _data.ArtifactField;
    /// <summary>
    /// 默认能力
    /// </summary>
     public int[] DefaultAbilities => _data.DefaultAbilities;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

